//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anuncio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Anuncio()
        {
            this.Contactoes = new HashSet<Contacto>();
            this.Transaccions = new HashSet<Transaccion>();
        }
    
        public int idAnuncio { get; set; }
        public string descripcion { get; set; }
        public System.DateTime fechaPublicacion { get; set; }
        public string tipoServicio { get; set; }
        public string localidad { get; set; }
        public int idUsuario { get; set; }
        public int idCategoria { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contacto> Contactoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaccion> Transaccions { get; set; }
        public virtual CategoriaDeServicio CategoriaDeServicio { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
