//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        public string idUsername { get; set; }
        public string idPassword { get; set; }
        public Nullable<int> idUsuario { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
