//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.Anuncios = new HashSet<Anuncio>();
            this.Sugerencias = new HashSet<Sugerencia>();
            this.Transaccions = new HashSet<Transaccion>();
            this.Transaccions1 = new HashSet<Transaccion>();
            this.Contactoes = new HashSet<Contacto>();
            this.Contactoes1 = new HashSet<Contacto>();
        }

        public Usuario(String nombre, String apellido1, String apellido2, String direccion, String localidad,
                String provincia, String email, String username, String password, int codigoPostal, int telefono)
        {
            this.nombre = nombre;
            this.apellido1 = apellido1;
            this.apellido2 = apellido2;
            this.direccion = direccion;
            this.localidad = localidad;
            this.provincia = provincia;
            this.email = email;
            this.idUsername = username;
            this.idPassword = password;
            this.codigoPostal = codigoPostal;
            this.telefono = telefono;
            this.balanceDeHoras = 3;  // Damos 3 horas de regalo por darse de alta en la app para poder probar
        }
    
        public int idUsuario { get; set; }
        public string nombre { get; set; }
        public string apellido1 { get; set; }
        public string apellido2 { get; set; }
        public string direccion { get; set; }
        public Nullable<int> codigoPostal { get; set; }
        public string localidad { get; set; }
        public string provincia { get; set; }
        public string email { get; set; }
        public Nullable<int> telefono { get; set; }
        public string idUsername { get; set; }
        public string idPassword { get; set; }
        public Nullable<int> balanceDeHoras { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Anuncio> Anuncios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sugerencia> Sugerencias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaccion> Transaccions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaccion> Transaccions1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contacto> Contactoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contacto> Contactoes1 { get; set; }
    }
}
